[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
uefi = { workspace = true, features = [
  "panic_handler",
  "logger",
  "alloc",
  "global_allocator",
] }
utils = { path = "../utils" }
bootlib = { path = "../bootlib" }
